export default [
    {
        "name": "Max Campos",
        "email": "max.campos@checkmat.com",
        "gender": "Male",
        "DOB": "21/06/1989",
        "weight": "70kg",
        "belt": "Black",
        "headshot": "https://res.cloudinary.com/dvp3fdavw/image/upload/v1737715880/max-campos_nsolc5.jpg",
        "instagram": "https://www.instagram.com/maxcamposbjj/",
        "facebook": "https://www.facebook.com/maxcamposbjj/"
    },
    {
        "name": "Mark Phung",
        "email": "mark.phung@fma.com",
        "gender": "Male",
        "DOB": "13/06/1979",
        "weight": "64kg",
        "belt": "Black",
        "headshot": "https://res.cloudinary.com/dvp3fdavw/image/upload/v1737715868/mark-phung_kiwrmg.jpg",
        "instagram": "https://www.instagram.com/farnham_martial_arts/",
        "facebook": "https://www.facebook.com/search/top?q=mark%20phung%20bjj"
    },
    {
        "name": "Kamran Raja",
        "email": "kamran.raja@hotmail.co.uk",
        "gender": "Male",
        "DOB": "26/06/1984",
        "weight": "77kg",
        "belt": "Purple",
        "headshot": "https://res.cloudinary.com/dvp3fdavw/image/upload/v1737716036/kamran-raja_nvq2sz.jpg",
        "instagram": "https://www.instagram.com/kamran.raja1982/?hl=en",
        "facebook": "https://www.facebook.com/kamran.raja.39/?locale=en_GB"
    },
    {
        "name": "Matt Debenham",
        "email": "matt.debenham@fma.com",
        "gender": "Male",
        "DOB": "20/12/1992",
        "weight": "91kg",
        "belt": "Purple",
        "headshot": "https://res.cloudinary.com/dvp3fdavw/image/upload/v1737716037/matt-debenham-bw_ine7g1.jpg",
        "instagram": "",
        "facebook": ""
    },
    {
        "name": "Joanna Miarczynska",
        "email": "joanna@fma.com",
        "gender": "Female",
        "DOB": "26/06/1980",
        "weight": "48kg",
        "belt": "Blue",
        "headshot": "https://res.cloudinary.com/dvp3fdavw/image/upload/v1737716037/joanna-miarczynska_tuzvzt.jpg",
        "instagram": "",
        "facebook": "https://www.facebook.com/joanna.miarczynska?locale=en_GB"
    },
    {
        "name": "Matt Arnold",
        "email": "matt.arnoldfma@fma.com",
        "gender": "Male",
        "DOB": "15/01/1992",
        "weight": "72kg",
        "belt": "Blue",
        "headshot": "https://res.cloudinary.com/dvp3fdavw/image/upload/v1737716038/matt-arnold_lvzkoi.jpg",
        "instagram": "https://www.instagram.com/mattttarnold/?hl=en",
        "facebook": ""
    },
    {
        "name": "Grant Bambrick-Day",
        "email": "grant@fma.com",
        "gender": "Male",
        "DOB": "10/01/1988",
        "weight": "82kg",
        "belt": "Purple",
        "headshot": "https://res.cloudinary.com/dvp3fdavw/image/upload/v1737716040/grant-bambrick-day_dwodes.jpg",
        "instagram": "https://www.instagram.com/bearded_vegetable/?hl=en",
        "facebook": "https://www.facebook.com/Grantus.Day?locale=en_GB"
    },
    {
        "name": "Adam Castley",
        "email": "adam.castley@fma.com",
        "gender": "Male",
        "DOB": "28/05/1994",
        "weight": "100kg",
        "belt": "Purple",
        "headshot": "https://res.cloudinary.com/dvp3fdavw/image/upload/v1737716040/adam-castley_zod6cf.jpg",
        "instagram": "https://www.instagram.com/castl38/?hl=en",
        "facebook": ""
    },
    {
        "name": "James Flett",
        "email": "james.flett@fma.com",
        "gender": "Male",
        "DOB": "23/01/1984",
        "weight": "87kg",
        "belt": "Blue",
        "headshot": "https://res.cloudinary.com/dvp3fdavw/image/upload/v1737716041/james-flett_rsxgmw.jpg",
        "instagram": "https://www.instagram.com/farmerflett/?hl=en",
        "facebook": "https://www.facebook.com/james.flett.18?locale=en_GB"
    },
    {
        "name": "Jamani Farrell",
        "email": "jam.farell@fma.com",
        "gender": "Female",
        "DOB": "13/11/1997",
        "weight": "70kg",
        "belt": "Blue",
        "headshot": "https://res.cloudinary.com/dvp3fdavw/image/upload/v1737716046/jamani-farrell_uk0czw.jpg",
        "instagram": "https://www.instagram.com/jaammaanni/?hl=en",
        "facebook": ""
    },
    {
        "name": "Carl Atkinson",
        "email": "carl.atkinson@fma.com",
        "gender": "Male",
        "DOB": "28/12/1978",
        "weight": "88kg",
        "belt": "Blue",
        "headshot": "https://res.cloudinary.com/dvp3fdavw/image/upload/v1737716042/carl_atkinson_auybx1.jpg",
        "instagram": "https://www.instagram.com/carlmadasafish/?hl=en",
        "facebook": "https://www.facebook.com/carlmadasafish?locale=en_GB"
    },
    {
        "name": "Matt Roberts",
        "email": "mattroberts.fma@hotmail.co.uk",
        "gender": "Male",
        "DOB": "18/05/1990",
        "weight": "88kg",
        "belt": "White",
        "headshot": "https://res.cloudinary.com/dvp3fdavw/image/upload/v1737716042/matt_roberts_iu1yfm.jpg",
        "instagram": "",
        "facebook": ""
    },
    {
        "name": "Clayton Knowles",
        "email": "Clayton.knowles@fma.com",
        "gender": "Male",
        "DOB": "21/11/1991",
        "weight": "92kg",
        "belt": "Brown",
        "headshot": "https://res.cloudinary.com/dvp3fdavw/image/upload/v1737716043/clayton_cbjogo.jpg",
        "instagram": "https://www.instagram.com/claytonjesse_k/?hl=en",
        "facebook": "https://www.facebook.com/clayton.j.knowles.9?locale=en_GB"
    },
    {
        "name": "Millie Oulton",
        "email": "millie.oulton@fma.com",
        "gender": "Female",
        "DOB": "15/01/1999",
        "weight": "62kg",
        "belt": "White",
        "headshot": "https://res.cloudinary.com/dvp3fdavw/image/upload/v1737716035/female_headshot_ntxmak.jpg",
        "instagram": "https://www.instagram.com/millieoulton/?hl=en",
        "facebook": "https://www.facebook.com/millie.oulton?locale=en_GB"
    },
    {
        "name": "Nuno Ramalho",
        "email": "nuno@fma.com",
        "gender": "Male",
        "DOB": "28/07/1975",
        "weight": "72kg",
        "belt": "Purple",
        "headshot": "https://res.cloudinary.com/dvp3fdavw/image/upload/v1737716044/nuno_s2g86i.jpg",
        "instagram": "https://www.instagram.com/njramalho/?hl=en",
        "facebook": ""
    },
    {
        "name": "Peter Woods",
        "email": "Peter.woods@fma.com",
        "gender": "Male",
        "DOB": "01/08/2001",
        "weight": "94kg",
        "belt": "White",
        "headshot": "https://res.cloudinary.com/dvp3fdavw/image/upload/v1737716036/male_headshot_dwklnh.jpg",
        "instagram": "https://www.instagram.com/_peter_woods/?hl=en",
        "facebook": ""
    },
    {
        "name": "John Cann",
        "email": "John.cann@fma.com",
        "gender": "Male",
        "DOB": "07/12/1986",
        "weight": "88kg",
        "belt": "Brown",
        "headshot": "https://res.cloudinary.com/dvp3fdavw/image/upload/v1737716044/john-cann_xsntjk.jpg",
        "instagram": "https://www.instagram.com/johncannpt/?hl=en",
        "facebook": ""
    },
    {
        "name": "Vincent Douthwaite",
        "email": "vincent@fma.com",
        "gender": "Male",
        "DOB": "28/09/1986",
        "weight": "85kg",
        "belt": "Blue",
        "headshot": "https://res.cloudinary.com/dvp3fdavw/image/upload/v1737716034/vincent-douthwaite_l2gv4a.jpg",
        "instagram": "https://www.instagram.com/vincent.k.d/?hl=en",
        "facebook": ""
    },
    {
        "name": "Kieran Daniel",
        "email": "kieran.daniel@fma.comm",
        "gender": "Male",
        "DOB": "02/06/1979",
        "weight": "88kg",
        "belt": "White",
        "headshot": "https://res.cloudinary.com/dvp3fdavw/image/upload/v1737716036/male_headshot_dwklnh.jpg",
        "instagram": "https://www.instagram.com/kieran30156/?hl=en",
        "facebook": ""
    }
]